"""agregar_auditoria_productos

Revision ID: 0b8b24ea56cf
Revises: 5b986fab1f8b
Create Date: 2026-04-17 18:44:02.317214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8b24ea56cf'
down_revision: Union[str, Sequence[str], None] = '5b986fab1f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('productos', sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('productos', sa.Column('creado_por', sa.String(length=100), nullable=True))
    op.add_column('productos', sa.Column('actualizado_por', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'actualizado_por')
    op.drop_column('productos', 'creado_por')
    op.drop_column('productos', 'actualizado_en')
    op.drop_column('productos', 'creado_en')
    # ### end Alembic commands ###
