"""agregar_activo_jornadas

Revision ID: 2098b9c1fddb
Revises: 0b8b24ea56cf
Create Date: 2026-04-17 18:55:54.064196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2098b9c1fddb'
down_revision: Union[str, Sequence[str], None] = '0b8b24ea56cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jornadas', sa.Column('activo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jornadas', 'activo')
    # ### end Alembic commands ###
