"""inicial

Revision ID: 5b986fab1f8b
Revises: 
Create Date: 2026-04-17 18:35:39.451698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b986fab1f8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'contrasena',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('jornadas', 'activo')
    op.drop_column('productos', 'actualizado_por')
    op.drop_column('productos', 'creado_en')
    op.drop_column('productos', 'creado_por')
    op.drop_column('productos', 'actualizado_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('creado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('actualizado_por', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('jornadas', sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.alter_column('empleados', 'contrasena',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
